<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql" Version="13.4.6" />
        <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.4.0" />
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
        
    </ItemGroup>

</Project>
